import ImgReactJS from "../public/features/reactjs.svg";
import ImgJS from "../public/features/javascript.svg";
import ImgNodeJS from "../public/features/nodejs.svg";
import ImgJava from "../public/features/java.svg";

export const foundation = [
  {
    serialNumber: "01",
    title: "Javascript",
    imageSrc: ImgJS,
    chapters: 20,
    courseType: "Free",
    description: `Learn all about React.js the frontend library. You will learn about Hooks, 
        State management, props, DOM, Virtual DOM, prop drilling and many more`,
    redirectLink: "/",
  },
  {
    serialNumber: "02",
    title: "Node JS",
    imageSrc: ImgNodeJS,
    chapters: 20,
    courseType: "Free",
    description: `Learn all about React.js the frontend library. You will learn about Hooks, 
        State management, props, DOM, Virtual DOM, prop drilling and many more`,
    redirectLink: "/",
  },
  {
    serialNumber: "03",
    title: "Java",
    imageSrc: ImgJava,
    chapters: 20,
    courseType: "Free",
    description: `Learn all about React.js the frontend library. You will learn about Hooks, 
          State management, props, DOM, Virtual DOM, prop drilling and many more`,
    redirectLink: "/",
  },
  {
    serialNumber: "04",
    title: "Node JS",
    imageSrc: ImgNodeJS,
    chapters: 20,
    courseType: "Free",
    description: `Learn all about React.js the frontend library. You will learn about Hooks, 
            State management, props, DOM, Virtual DOM, prop drilling and many more`,
    redirectLink: "/",
  },
  {
    serialNumber: "05",
    title: "React JS",
    imageSrc: ImgReactJS,
    chapters: 20,
    courseType: "Free",
    description: `Learn all about React.js the frontend library. You will learn about Hooks, 
              State management, props, DOM, Virtual DOM, prop drilling and many more`,
    redirectLink: "/",
  },
  {
    serialNumber: "01",
    title: "Javascript",
    imageSrc: ImgJS,
    chapters: 20,
    courseType: "Free",
    description: `Learn all about React.js the frontend library. You will learn about Hooks, 
        State management, props, DOM, Virtual DOM, prop drilling and many more`,
    redirectLink: "/",
  },
  {
    serialNumber: "02",
    title: "Node JS",
    imageSrc: ImgNodeJS,
    chapters: 20,
    courseType: "Free",
    description: `Learn all about React.js the frontend library. You will learn about Hooks, 
        State management, props, DOM, Virtual DOM, prop drilling and many more`,
    redirectLink: "/",
  },
  {
    serialNumber: "03",
    title: "Java",
    imageSrc: ImgJava,
    chapters: 20,
    courseType: "Free",
    description: `Learn all about React.js the frontend library. You will learn about Hooks, 
          State management, props, DOM, Virtual DOM, prop drilling and many more`,
    redirectLink: "/",
  },
  {
    serialNumber: "04",
    title: "Node JS",
    imageSrc: ImgNodeJS,
    chapters: 20,
    courseType: "Free",
    description: `Learn all about React.js the frontend library. You will learn about Hooks, 
            State management, props, DOM, Virtual DOM, prop drilling and many more`,
    redirectLink: "/",
  },
  {
    serialNumber: "05",
    title: "React JS",
    imageSrc: ImgReactJS,
    chapters: 20,
    courseType: "Free",
    description: `Learn all about React.js the frontend library. You will learn about Hooks, 
              State management, props, DOM, Virtual DOM, prop drilling and many more`,
    redirectLink: "/",
  },
];
